### ISSUE TITLE
👍

### ISSUE THREAD

**Issue by NobUwU** [SakiyaDev/dotlang-with-line-break#1]
I did not realize this was an issue. Would be much appreciated if you could pull request this fix and receive attribution.

**Comment by EmiliaShiori** [comment]
I can try to contact my friend who made this, but he would probs answer you faster on discord

**Comment by tsukuyomiotoko** [comment]
> I did not realize this was an issue. Would be much appreciated if you could pull request this fix and receive attribution.

Hey, I'm sure we can come to an agreement on discord. Add me `Sasuke the Therapist#7872`

**Comment by EmiliaShiori** [comment]
> > Hey, I'm sure we can come to an agreement on discord. Add me `Sasuke the Therapist#7872`
> 
> I would prefer to chat in a guild instead if that is okay.

We have a server if you wanta join, discord.gg/sakiya, or you can send us an invite
